import { LitiDocAnalysisResponse } from "./types";

export const mockAnalysisData: LitiDocAnalysisResponse = {
  caseName: "Johnson v. Costco",
  parties: {
    plaintiff: "Mike Johnson / Mike Smith",
    defendant: "Costco Wholesale Corporation",
  },
  matterType: "Wrongful dismissal / constructive dismissal / disability-related termination",
  jurisdiction: "Ontario",
  currentStage: "Analysis complete",
  nameInconsistencyNote: "Name inconsistency detected across source documents: Statement of Claim names Mike Johnson, supporting employment, medical, and financial records name Mike Smith. Flagged for review.",
  extractedEvents: 12,
  damageCategories: 7,
  sourcesCited: 24,
  documentIndex: [
    {
      ref: "1.1",
      file: "Statement_of_Claim_Johnson_v_Costco.pdf",
      type: "Pleading",
      summary: "Pleading alleging wrongful dismissal, constructive dismissal, bad faith, disability discrimination, lost benefits, and lost bonus compensation.",
      pages: 5,
    },
    {
      ref: "2.1",
      file: "Deposition_Director_Holt_Johnson_v_Costco.pdf",
      type: "Discovery Transcript",
      summary: "Examination of Richard Holt, Regional Finance Director, covering performance history, reassignment of duties, demotion, internal complaint, medical leave, and termination decision.",
      pages: 13,
    },
    {
      ref: "3.1",
      file: "3_Employment_Contract.pdf",
      type: "Employment Record",
      summary: "Employment agreement for Senior Accountant role with $85,000 starting salary and no termination clause.",
      pages: 2,
    },
    {
      ref: "3.2",
      file: "4_Performance_Reviews_Compilation.pdf",
      type: "HR Record",
      summary: "HR record showing strong Year 3/4 reviews followed by weaker Year 5 review.",
      pages: 1,
    },
    {
      ref: "3.3",
      file: "7_HR_Non_Response_to_Complaint.pdf",
      type: "Correspondence",
      summary: "Email acknowledging complaint and noting no further investigation follow-up in plaintiff note.",
      pages: 1,
    },
    {
      ref: "3.4",
      file: "8_Demotion_Memo.pdf",
      type: "HR Record",
      summary: "Internal memo changing title, reporting structure, supervisory duties, salary status, and workspace.",
      pages: 1,
    },
    {
      ref: "3.5",
      file: "9_Termination_Letter_During_Leave.pdf",
      type: "Correspondence",
      summary: "Letter terminating employment without cause while employee was on medical leave.",
      pages: 1,
    },
    {
      ref: "3.6",
      file: "10_Internal_Complaint_Mike.pdf",
      type: "HR Record",
      summary: "Formal complaint alleging workplace harassment, marginalization, and constructive dismissal.",
      pages: 1,
    },
    {
      ref: "4.1",
      file: "5_Benefits_Plan_Summary_Coverage.pdf",
      type: "Benefits Record",
      summary: "Benefits plan summary showing health, dental, life insurance, STD, and RRSP match.",
      pages: 1,
    },
    {
      ref: "4.2",
      file: "6_Benefits_Plan_Summary_Bonus.pdf",
      type: "Compensation Record",
      summary: "Compensation plan showing target bonus of 15% and maximum payout of 25%.",
      pages: 1,
    },
    {
      ref: "4.3",
      file: "1_T4_Statement_of_Remuneration.pdf",
      type: "Financial Record",
      summary: "Financial record showing 2025 employment income of $115,400 and no management bonus paid.",
      pages: 1,
    },
    {
      ref: "4.4",
      file: "2_Record_of_Employment_Income_Stopped.pdf",
      type: "Financial Record",
      summary: "Payroll record confirming income stopped May 10, 2026 due to termination without cause.",
      pages: 1,
    },
    {
      ref: "5.1",
      file: "11_Physician_Note_Diagnosis.pdf",
      type: "Medical Record",
      summary: "Medical certificate diagnosing anxiety/depression and placing employee on medical leave.",
      pages: 1,
    },
    {
      ref: "5.2",
      file: "12_Short_Term_Disability_Approval.pdf",
      type: "Benefits / Medical Leave Record",
      summary: "Disability approval letter confirming STD benefits at 70% of weekly base salary.",
      pages: 1,
    },
  ],
  timeline: [
    {
      date: "January 5, 2018",
      event: "Mike Smith entered an employment agreement with Costco as Senior Accountant in the corporate finance division.",
      people: "Mike Smith, Costco",
      citation: "Doc 3.1, p. 1",
      confidence: "High",
    },
    {
      date: "Year 3 / 2020",
      event: "Mike received an \"Exceeds Expectations\" performance review.",
      people: "Mike Smith",
      citation: "Doc 3.2, p. 1",
      confidence: "High",
    },
    {
      date: "Year 4 / 2021",
      event: "Mike was promoted to Accounting Manager and received an \"Outstanding\" performance review.",
      people: "Mike Smith",
      citation: "Doc 3.2, p. 1",
      confidence: "High",
    },
    {
      date: "Year 5",
      event: "Richard Holt joined Costco as Regional Finance Director and became responsible for the Ontario finance team.",
      people: "Richard Holt",
      citation: "Doc 2.1, p. 3",
      confidence: "High",
    },
    {
      date: "Year 5",
      event: "Holt acknowledged that Johnson had positive earlier reviews, merit increases, and a promotion before Holt arrived.",
      people: "Richard Holt, Mike Johnson",
      citation: "Doc 2.1, p. 4",
      confidence: "High",
    },
    {
      date: "Year 5",
      event: "Holt gave Johnson his first negative review, but acknowledged the concerns were not documented in writing before the review and no performance improvement plan had been issued.",
      people: "Richard Holt, Mike Johnson",
      citation: "Doc 2.1, p. 6",
      confidence: "High",
    },
    {
      date: "March 2, 2024",
      event: "Costco changed Mike's title from Accounting Manager to Senior Accountant, revoked supervisory responsibilities, froze salary, and changed reporting structure.",
      people: "Mike Smith, Regional Finance Director",
      citation: "Doc 3.4, p. 1",
      confidence: "High",
    },
    {
      date: "Year 6",
      event: "Holt confirmed that some of Johnson's core duties were reassigned without advance consultation and without a revised job description.",
      people: "Richard Holt, Mike Johnson",
      citation: "Doc 2.1, p. 7",
      confidence: "High",
    },
    {
      date: "Year 7",
      event: "Holt confirmed Johnson's title changed from Accounting Manager to Senior Accountant and acknowledged that this was technically a lower title.",
      people: "Richard Holt, Mike Johnson",
      citation: "Doc 2.1, p. 9",
      confidence: "High",
    },
    {
      date: "October 12, 2024",
      event: "Mike submitted a formal internal complaint alleging workplace harassment and constructive dismissal.",
      people: "Mike Smith, HR",
      citation: "Doc 3.6, p. 1",
      confidence: "High",
    },
    {
      date: "October 14, 2024",
      event: "HR acknowledged receipt of the complaint and stated it would be investigated.",
      people: "Mike Smith, HR Shared Services",
      citation: "Doc 3.3, p. 1",
      confidence: "High",
    },
    {
      date: "November 5, 2024",
      event: "Physician diagnosed Mike with acute anxiety and depression attributed to workplace stress and placed him on medical leave.",
      people: "Mike Smith, Dr. Sarah Adams",
      citation: "Doc 5.1, p. 1",
      confidence: "High",
    },
    {
      date: "November 15, 2024",
      event: "Short-term disability benefits were approved effective November 5, 2024 at 70% of weekly base salary.",
      people: "Mike Smith, SunLife / Costco Benefits Administration",
      citation: "Doc 5.2, p. 1",
      confidence: "High",
    },
    {
      date: "May 10, 2026",
      event: "Costco terminated Mike's employment without cause while acknowledging he was on medical leave and receiving STD benefits.",
      people: "Mike Smith, Costco HR",
      citation: "Doc 3.5, p. 1",
      confidence: "High",
    },
    {
      date: "May 2026",
      event: "Holt confirmed he was aware Johnson was on medical leave when the termination letter was delivered and that he supported the termination decision.",
      people: "Richard Holt, Mike Johnson",
      citation: "Doc 2.1, p. 11",
      confidence: "High",
    },
    {
      date: "May 12, 2026",
      event: "Record of Employment confirmed income ceased effective May 10, 2026 due to dismissal / termination without cause.",
      people: "Mike Smith, Costco Payroll",
      citation: "Doc 4.4, p. 1",
      confidence: "High",
    },
    {
      date: "May 28, 2026",
      event: "Statement of Claim was filed alleging wrongful dismissal, constructive dismissal, bad faith, disability discrimination, lost wages, benefits, bonus, and other damages.",
      people: "Mike Johnson, Costco",
      citation: "Doc 1.1, pp. 2-5",
      confidence: "High",
    },
    {
      date: "July 14, 2026",
      event: "Holt acknowledged that the negative review, responsibility reassignment, salary freeze, warning, demotion, and termination during medical leave occurred, while disputing the plaintiff's characterization of those events.",
      people: "Richard Holt, Mike Johnson",
      citation: "Doc 2.1, p. 12",
      confidence: "High",
    },
  ],
  backgroundDraft: `Mike Smith entered into an employment agreement with Costco Wholesale Corporation on January 5, 2018, for the position of Senior Accountant within the corporate finance division (Doc 3.1, p. 1). The agreement provided for a starting base salary of $85,000 per annum and participation in Costco's corporate benefits plan (Doc 3.1, p. 1). The agreement did not contain a termination clause limiting common law reasonable notice (Doc 3.1, p. 1).

The employment records indicate that Mr. Smith received positive performance reviews in Year 3 and Year 4, including an "Exceeds Expectations" review in 2020 and an "Outstanding" review in 2021, the year he was promoted to Accounting Manager (Doc 3.2, p. 1). On March 2, 2024, Costco issued an internal memorandum changing his title from Accounting Manager to Senior Accountant, revoking his supervisory responsibilities, freezing his base salary, and changing his reporting structure (Doc 3.4, p. 1).

In examination, Richard Holt confirmed that Mr. Johnson had received positive reviews, merit increases, and a promotion before Holt became Regional Finance Director (Doc 2.1, p. 4). Holt also confirmed that the concerns underlying the first negative review were not documented in writing before the review, that no performance improvement plan had been issued at that stage, and that certain core duties were later reassigned without advance consultation or a revised job description (Doc 2.1, pp. 6-7). Holt further acknowledged that the title change from Accounting Manager to Senior Accountant was technically a lower title (Doc 2.1, p. 9).

On October 12, 2024, Mr. Smith submitted a formal internal complaint alleging workplace harassment, marginalization, demotion without business justification, and constructive dismissal (Doc 3.6, p. 1). HR acknowledged receipt of the complaint on October 14, 2024 and stated that it would be reviewed and investigated in due course (Doc 3.3, p. 1). The source materials indicate that no further correspondence, investigation findings, or follow-up communications were provided (Doc 3.3, p. 1).

On November 5, 2024, Dr. Sarah Adams diagnosed Mr. Smith with acute anxiety and depression attributed to workplace stress and placed him on an immediate medical leave of absence for no less than eight weeks (Doc 5.1, p. 1). On November 15, 2024, SunLife / Costco Benefits Administration approved Mr. Smith's short-term disability benefits effective November 5, 2024 at 70% of weekly base salary (Doc 5.2, p. 1).

On May 10, 2026, Costco terminated Mr. Smith's employment without cause, while acknowledging that he was on medical leave and receiving short-term disability benefits (Doc 3.5, p. 1). Holt later confirmed that he was aware Mr. Johnson was on medical leave when the termination letter was delivered and that he supported the termination decision (Doc 2.1, p. 11). The termination letter stated that Costco would provide statutory minimum entitlements under the Employment Standards Act, 2000, with no additional severance pay or common law notice offered (Doc 3.5, p. 1). A Record of Employment issued May 12, 2026 confirmed that regular salary and wage payments ceased effective May 10, 2026 due to dismissal or termination without cause (Doc 4.4, p. 1).

The Statement of Claim filed May 28, 2026 advances claims for wrongful dismissal, constructive dismissal, statutory termination and severance pay, bad faith damages, disability-related damages, lost benefits, lost bonus compensation, pre-judgment interest, post-judgment interest, and costs (Doc 1.1, pp. 2-5). A name discrepancy is noted in the source materials: the Statement of Claim identifies the plaintiff as Mike Johnson, while supporting employment, medical, and financial records identify the employee as Mike Smith. This discrepancy should be reviewed before the draft is finalized.`,
  damageRegister: [
    {
      category: "Wrongful Dismissal / Reasonable Notice Damages",
      description: "Compensation allegedly owed for salary and wages during the common law reasonable notice period.",
      extractedSupport: "Employment contract contains no termination clause limiting common law reasonable notice, and termination letter offered statutory minimums only.",
      citation: "Doc 3.1, p. 1; Doc 3.5, p. 1",
      notes: "Requires reasonable notice assessment and mitigation review.",
    },
    {
      category: "Constructive Dismissal Damages",
      description: "Damages arising from alleged unilateral changes to role, status, reporting structure, supervisory responsibilities, salary progression, and working conditions.",
      extractedSupport: "Demotion memo changed title from Accounting Manager to Senior Accountant, revoked supervisory responsibilities, froze salary, and changed reporting line. Holt's deposition also confirms reassignment without advance consultation, no revised job description, and lower title.",
      citation: "Doc 3.4, p. 1; Doc 2.1, pp. 7-9",
      notes: "Requires legal assessment of whether changes were fundamental.",
    },
    {
      category: "Lost Benefits",
      description: "Value of health, dental, life insurance, STD coverage, and pension/RRSP matching allegedly lost during the notice period.",
      extractedSupport: "Benefits plan summary shows employer-paid health, dental, life insurance, STD coverage, and RRSP match.",
      citation: "Doc 4.1, p. 1",
      notes: "Requires valuation over reasonable notice period.",
    },
    {
      category: "Lost Bonus / Incentive Compensation",
      description: "Potential loss of annual or incentive bonus compensation during the notice period.",
      extractedSupport: "Bonus plan summary shows target bonus of 15% of annual base salary and maximum payout of 25%.",
      citation: "Doc 4.2, p. 1",
      notes: "Requires review of bonus eligibility and common law entitlement.",
    },
    {
      category: "Disability / Human Rights-Related Damages",
      description: "Claimed damages arising from alleged termination during medical leave and treatment connected to disability.",
      extractedSupport: "Physician note diagnosed acute anxiety and depression; STD benefits were approved; termination letter acknowledged employee was on medical leave. Holt also acknowledged he knew Johnson was on leave when termination was delivered.",
      citation: "Doc 5.1, p. 1; Doc 5.2, p. 1; Doc 3.5, p. 1; Doc 2.1, p. 11",
      notes: "Requires legal review under the Ontario Human Rights Code.",
    },
    {
      category: "Bad Faith / Manner of Dismissal Damages",
      description: "Claimed damages for alleged bad faith conduct in the employment relationship and manner of dismissal.",
      extractedSupport: "Internal complaint alleges workplace harassment, marginalization, demotion, and threatened termination; HR acknowledgment indicates complaint was logged. Deposition evidence references no formal PIP, no documented measurable targets, and termination during medical leave.",
      citation: "Doc 3.6, p. 1; Doc 3.3, p. 1; Doc 2.1, pp. 10-12",
      notes: "Requires review of causation and evidence of mental distress.",
    },
    {
      category: "Statutory Termination / Severance Pay",
      description: "ESA entitlements arising from termination without cause.",
      extractedSupport: "Termination letter offered statutory minimum termination pay only; ROE confirms termination without cause and income cessation.",
      citation: "Doc 3.5, p. 1; Doc 4.4, p. 1",
      notes: "Requires statutory calculation based on service and payroll.",
    },
  ],
};
